### ISSUE TITLE
APK availability outside Playstore?

### ISSUE THREAD

**Issue by IzzySoft** [Helltar/ANPASIDE#3]
Would you consider making the APK available outside Playstore (e.g. attaching it to your tags/releases), so folks without Playstore access could use your app as well? Thanks in advance!

**Comment by Helltar** [comment]
Hi, done:

- https://github.com/Helltar/ANPASIDE/releases/download/v1.2-12/anpaside-1.2-12.apk

**Comment by IzzySoft** [comment]
Thanks a lot! That was fast :green_heart: But do you have any idea why so many scanners mark the app as dangerous? I've just run the APK through [VT](https://www.virustotal.com/gui/file/c0658bcc33897abd8d9377edd6dea4deec81a7cb1e96648c83fe3707535e9901/detection/f-c0658bcc33897abd8d9377edd6dea4deec81a7cb1e96648c83fe3707535e9901-1636756591), and the report shows 11 engines suspecting an issue; not just the minor ones but also major engines as AVG, Avast, BitDefender and GData. Could some dependency have dragged something in?

**Comment by Helltar** [comment]
@IzzySoft yes, this is a long-standing problem in midletpascal classes: https://github.com/Helltar/ANPASIDE/tree/master/app/src/main/assets/stubs

Back in the days of JavaME, a malware was written on it that sends SMS to paid numbers, this problem is described in the Russian wikipedia: https://ru.wikipedia.org/wiki/MIDletPascal#%D0%A1%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F_%D0%B0%D0%BD%D1%82%D0%B8%D0%B2%D0%B8%D1%80%D1%83%D1%81%D0%BE%D0%B2

Here is the source code of these classes: https://sourceforge.net/p/midletpascal/code/HEAD/tree/MPS.3.1/

There's nothing terrible there

**Comment by IzzySoft** [comment]
Thanks for the details! That indeed explains (and one more time justifies why one should be careful interpreting such scanner results). As for the description, and because my Russian is very limited, could you please "proof-read" (and, if necessary, correct):

> Примечание: классы MidletPascal вызывают ложные срабатывания в многочисленных сканерах вредоносного ПО. На сайте Русская Википедия описывает эту проблему: Упомянутое вредоносное ПО содержит классы MidletPascal, а не наоборот.

Background: to make your app easier to be discovered and kept up-to-date by "non-Googlers", I've just added it to my F-Droid compatible repo (which is quite well-known by this target group). They'd be shocked seeing an app with so many "scanner warnings" – there is only one other such case, a security app for finding vulnerabilities which of course triggers such things. So as with that other app, I need to point out why the app was not removed but those scanner results can rather be "disregarded", hence I added that to the descriptions (EN & DE). You proved a RU description, so I need to amend that as well :smile:

That said: Your app should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.github.helltar.anpaside) in less than 3 hours from now. Updates will be fetched automatically as soon as you made them available by tagging and attaching the APK. If you want to link there, be welcome to use [my badges](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it).

**Comment by Helltar** [comment]
@IzzySoft 

> could you please "proof-read" (and, if necessary, correct):

_Some versions of antivirus programs (Norton, McAfee, etc.) report any program written in MIDletPascal as a virus "Trojan.Redbrowser.A". This is due to the fact that a Trojan program RedBrowser was written using MIDletPascal, secretly sending SMS messages._

**Comment by IzzySoft** [comment]
Thanks – I rather meant whether the Russian sentence I've quoted is "proper Russian" or needs to be modified :smile:
