### ISSUE TITLE
Add in app pascal preview

### ISSUE THREAD

**Issue by m-anshuman2166** [Helltar/ANPASIDE#4]
An option to preview pascal in app itself would be nice

Cool project btw...

**Comment by Helltar** [comment]
Hi, thanks, can you be more detailed, I'm not quite sure what you mean?

**Comment by m-anshuman2166** [comment]
For now it refers to app named `J2ME Emulator` which, doesnt work on android 11, you could use sources of https://github.com/nikita36078/J2ME-Loader and add an option inside app so that we can preview pascal code in app itself and no need to download any 3rd party apps

**Comment by Helltar** [comment]
There was an idea to do that originally, but I took the easy way out. But if J2MELoader doesn't work on Android 11, it seems better to wait for the author to fix it, because even if I add it to my code nothing will change, it's probably a problem with new Android 11 file access policy.

I'll take a look.

**Comment by Helltar** [comment]
I looked, the problem when running programs on Android 11 is not in the J2MELoader itself, but in ANPASIDE, I will fix it.

**Comment by Helltar** [comment]
I looked in more detail, the problem is still in J2MELoader, namely in the latest version 1.7.5, with 1.7.4 all works: https://github.com/nikita36078/J2ME-Loader/releases/tag/1.7.4

Created issue, waiting for response: https://github.com/nikita36078/J2ME-Loader/issues/905

**Comment by m-anshuman2166** [comment]
Okay, btw it would still be better if app is independent, rest on you friend :)
