### ISSUE TITLE
Синтаксическая ошибка

### ISSUE THREAD

**Issue by tellts** [Helltar/ANPASIDE#6]
ANPASIDE 1.5-25
Андроид 4.2 на планшете с диагональю примерно 10
Не запускается apk файл для установки, вылазит сообщение с текстом:
Синтаксическая ошибка
Ошибка при синтаксическом анализе пакета.

Версия 1.2 также не устанавливается.

**Comment by Helltar** [comment]
> Андроид 4.2
Данная версия не тестировалась из-за своей древности, на данный момент минимальная версия >= 7.

**Comment by Helltar** [comment]
Я посмотрю, возможно будет достаточно просто понизить минимальную версию в манифесте.

**Comment by tellts** [comment]
Благодарю. Буду ждать.
